services:
  backend:
    container_name: dualnets_backend
    hostname: dualnets.docker.dev
    build:
      context: .
      dockerfile: docker/dualnets.dockerfile
    environment:
      - VIRTUAL_HOST=dualnets.docker.dev
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    volumes:
      - ./:/var/www
    networks:
      - default
      - hts-appteam-local-dev
    env_file:
      - docker/keys.env
  frontend:
      container_name: dualnets_frontend
      build:
          dockerfile: docker/frontend.dockerfile
      volumes:
          - ./:/var/www/public
      working_dir: /var/www/public
      ports:
          - "7038:7038"
      networks:
          - default
          - hts-appteam-local-dev
  mariadb:
    hostname: dualnets_mariadb.docker
    container_name: dualnets_mariadb
    image: "mariadb:latest"
    ports:
      - "8038:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "development"
      MYSQL_USER: "development"
      MYSQL_PASSWORD: "secret"
  mariadbtest:
    hostname: dualnets_mariadb_test.docker
    container_name: dualnets_mariadb_test
    image: "mariadb:latest"
    ports:
      - "6038:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "secret"
networks:
  hts-appteam-local-dev:
    external: true

